version: '3'
services:
  myapp-main:
    image: golf_club_tournament_api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_club_db_2025
      - spring.datasource.password=Moh60683
      - spring.datasource.username=root